FIx [Bower] service test
  3) Bower
       custom label for pre version. eg. pre verison|v0.2.5-alpha-rc-pre

	[ GET http://localhost:1111/bower/vpre/bootstrap.json?label="pre verison" ]:
     ValidationError: child "value" fails because ["value" with value "v4.0.0-beta.2" fails to match the required pattern: /^v\d+(\.\d+)?(\.\d+)?(-?\w)+?$/]